[build]
  publish = "." # This tells Netlify to publish the contents of the repository root directly
  command = "npm install" # You still need to run npm install for your Netlify Functions' dependencies
  functions = "netlify/functions"