backend:
  name: github
  repo: mohan-site/mohan-site # Your GitHub username/repo name
  branch: main # Or master
  auth_proxy_url: https://mohan-site.netlify.app/.netlify/functions/your-auth-function-name # This is where Decap CMS will send auth requests

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string"}
          - {label: "Latest Book Image", name: "hero_img", widget: "image"}
          - {label: "Amazon Link", name: "hero_link", widget: "string"}